config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  "users#index"
  resources :users, :only => [:index, :show]
  resources :posts, :only => [:create] do
    resources :comments
  end
  resources :posts, :only => [:create, :new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
  end

   def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user
    redirect_to users_path
    # respond_to do |format|
    #   format.html { redirect_to book_show_url(book) }
    #   format.js {}
    # end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.photos.attach(params[:post][:photos])
    if @post.save
     redirect_to user_path(current_user) 
    end
  end

  private

  def post_params
    params.require(:post).permit(:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id).reverse
    @post = Post.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li>
    <p>
    <%= comment.user.name %>
  </p>
  <p>
    <%= comment.body %>
  </p>
</li>

app/views/comments/_form.html.erb
<%= form_with scope: :comment, url: [post, post.comments.build] do |f| %>
<div class="form-group">
  Текст: <%= f.text_area :body %>
</div>
<%= f.submit 'Отправить', class: 'btn table-primary border border-primary'  %>
<% end %>

app/views/comments/create.js.erb
$("#comments").append("<%= j render @comment %>");

app/views/comments/new.html.erb
<%= form_with scope: :comment, url: [@post, @post.comments.build] do |f| %>
<div class="form-group">
  Текст: <%= f.text_area :body %>
</div>
<%= f.submit 'Отправить', class: 'btn table-primary border border-primary'  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Insta</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="bg-light">
  <div class="container">
    <div class="d-flex">
    <h1 class="py-3 text-center w-75"><%= link_to 'INSTA', users_path, class: 'pt-4' %></h1>
      <% if user_signed_in? %>
        <%= link_to image_tag("icon.png", width: '40', height: '40'), user_path(current_user), class: 'pt-4' %>
    <% end %>
    </div>
    <hr>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="input-group">
  <%= form_with model: @post, local: true do |f| %>
    <%= f.label :photos, 'фотографии', class: 'custom-file-label'  %>
    <%= f.file_field :photos, class: 'custom-file-input', multiple: true  %>

    <%= f.text_area :description, placeholder: 'коментарий', class: 'form-control' %>

    <%= f.submit 'Отправить', class: 'btn  border border-primary' %>
  <% end %>
</div>

app/views/users/index.html.erb
<% if user_signed_in? %>
<% @users.each do |user| %>
<p>
  <% if user.avatar.attached? %>
  <%= image_tag user.avatar, size: "60x60", class: 'rounded-circle' %>
  <% end %>
  <%= link_to user.name, user_path(user)%>
</p>
<% end %>
<% else %>
<div class="nav-item d-flex justify-content-center py-5">
  <%= link_to 'Войти', new_user_session_path, class: 'nav-link btn table-primary border border-primary w-25' %>
</div>

<p class="text-center">Еще нет аккаунта:</p>
<div class="nav-item d-flex justify-content-center">
  <%= link_to 'Зарегистрируйтесь', new_user_registration_path, class: 'nav-link btn table-primary border border-primary w-25' %>
</div>
<% end %>

app/views/users/show.html.erb
<% if @user.id ==  current_user.id%>
<div class="text-center d-flex justify-content-between pb-5">
  <span class="text-uppercase">
    <% if current_user.avatar.attached? %>
    <%= image_tag current_user.avatar, size: "60x60", class: 'rounded-circle' %>
    <% end %>
    <%= current_user.name %>
  </span>
  <div>
    <p>Добавить фото в ленту</p>
    <%= render 'posts/form' %>
  </div>
  <nav>
    <%= link_to image_tag("edit.png", width: '40', height: '40'), edit_user_registration_path(current_user), class: 'pt-4' %>
    <%= link_to image_tag("logout.png", width: '40', height: '40'), destroy_user_session_path, method: :delete, class: 'pt-4' %>
  </nav>
</div>
<% else %>
<span class="text-uppercase">
  <% if @user.avatar.attached? %>
  <%= image_tag @user.avatar, size: "60x60", class: 'rounded-circle' %>
  <% end %>
  <%= @user.name%>
</span>
<% end %>

<% @posts.each_with_index do |post, index| %>
  <div class='py-5 d-flex justify-content-between border-bottom border-top'>
    <% if post.photos.attached? %>
    <span>
      <div id="carouselExampleControls<%= index %>" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag post.photos.first, size: "200x200", class: "d-block"  %>
          </div>
          <% post.photos.drop(1).each do |photo| %>
            <div class="carousel-item">
              <%= image_tag photo, size: "200x200", class: "d-block"    %>
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls<%= index %>" role="button" data-slide="prev">
          <!-- <span class="carousel-control-prev-icon" aria-hidden="true"></span> -->
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls<%= index %>" role="button" data-slide="next">
          <!-- <span class="carousel-control-next-icon" aria-hidden="true"></span> -->
          <span class="sr-only">Next</span>
        </a>
      </div>
      <%= post.user.name %>:
      <%= post.description %>
</span>
    <% end %>
    
  <ol id="comments">
    <p>Коментарии:</p>
    <%= render post.comments %>
  </ol>


<%= link_to 'новый коментарий', new_post_comment_path(post), class: 'pt-4' %>



  <%= form_with scope: :comment, url: [post, post.comments.build] do |f| %>
    <div class="form-group">
          <%= f.text_area :body, placeholder: 'добавить коментарий', class: 'form-control' %>
    </div>
    <%= f.submit 'Отправить', class: 'btn border border-primary' %>
  <% end %>
</div>
<% end %>